"""add unique constraint to like

Revision ID: 57cd262781d5
Revises: 4d9e19b8bf45
Create Date: 2026-06-12 12:21:54.375769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cd262781d5'
down_revision: Union[str, Sequence[str], None] = '4d9e19b8bf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_post_like', 'likes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_post_like', 'likes', type_='unique')
    # ### end Alembic commands ###
